# -*- coding: utf-8 -*-
"""midsem_project_titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mZOtBbZm7C97alsnnm_okX3YegRVKK0m

## Task 1: Data Acquisition
"""

import pandas as pd
df = pd.read_csv('train.csv')
print("Dataset loaded successfully.")

"""### 1. Dataset dimensions"""

print(f"Dataset dimensions (rows, columns): {df.shape}")

"""### 2. Column names"""

print("Column names:")
for col in df.columns:
    print(f"- {col}")

"""### 3. First five observations"""

display(df.head())

"""### 4. Data types"""

print("Data types:")
display(df.info())

"""## Task 2: Data Cleaning

### Detect missing values
"""

print("Missing values before cleaning:")
print(df.isnull().sum())

"""### Handle missing values appropriately"""

# Impute 'Age' with the median
df['Age'].fillna(df['Age'].median(), inplace=True)

# Impute 'Embarked' with the mode
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

print("Missing values after cleaning:")
print(df.isnull().sum())

print("\nDataFrame info after cleaning:")
df.info()

"""###Detect duplicated observations

"""

duplicated_rows = df.duplicated().sum()
print(f"Number of duplicated rows before removal: {duplicated_rows}")

"""###Remove duplicates if any exist"""

if duplicated_rows > 0:
    df.drop_duplicates(inplace=True)
    print(f"Number of duplicated rows after removal: {df.duplicated().sum()}")
else:
    print("No duplicated rows found.")

"""## Task 3: Data Visualisation

### 1. Histogram of passenger ages
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(df['Age'], bins=20, kde=True)
plt.title('Distribution of Passenger Ages')
plt.xlabel('Age')
plt.ylabel('Number of Passengers')
plt.grid(axis='y', alpha=0.75)
plt.show()

print("Interpretation: The histogram shows that the majority of passengers are young adults, primarily in their 20s and 30s. There's a notable peak around ages 20-30, and fewer passengers in the older age groups. Children are also present in significant numbers.")

"""### 2. Bar chart showing passenger class distribution"""

plt.figure(figsize=(8, 5))
sns.countplot(x='Pclass', data=df, palette='viridis')
plt.title('Distribution of Passenger Classes')
plt.xlabel('Passenger Class (1 = 1st, 2 = 2nd, 3 = 3rd)')
plt.ylabel('Number of Passengers')
plt.xticks([0, 1, 2], ['1st Class', '2nd Class', '3rd Class'])
plt.grid(axis='y', alpha=0.75)
plt.show()

print("Interpretation: This bar chart illustrates the count of passengers in each class. It's clear that the majority of passengers were in 3rd class, followed by 1st class, and then 2nd class. This uneven distribution could impact survival rates.")

"""### 3. Boxplot of age by passenger class

### 4. Scatter plot of Age versus Fare
"""

plt.figure(figsize=(10, 6))
sns.boxplot(x='Pclass', y='Age', data=df, palette='coolwarm')
plt.title('Age Distribution by Passenger Class')
plt.xlabel('Passenger Class (1 = 1st, 2 = 2nd, 3 = 3rd)')
plt.ylabel('Age')
plt.xticks([0, 1, 2], ['1st Class', '2nd Class', '3rd Class'])
plt.grid(axis='y', alpha=0.75)
plt.show()

print("Interpretation: The boxplot illustrates the age distribution across different passenger classes. It appears that passengers in 1st class tend to be older than those in 2nd and 3rd class. The median age generally decreases from 1st to 3rd class, suggesting that higher classes might have had older, potentially wealthier, individuals.")

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Age', y='Fare', data=df, hue='Survived', alpha=0.7)
plt.title('Age vs. Fare with Survival Status')
plt.xlabel('Age')
plt.ylabel('Fare')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

print("Interpretation: This scatter plot visualizes the relationship between Age and Fare, with points colored by survival status. It's difficult to discern a clear linear relationship between age and fare. However, there are some high-fare outliers, many of whom survived, and a dense cluster of lower-fare passengers across various ages.")

"""### 5. Correlation Heatmap"""

plt.figure(figsize=(12, 8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap of Numerical Features')
plt.show()

print("Interpretation: The heatmap displays the correlation coefficients between all numerical features. Positive values indicate a positive correlation, negative values indicate a negative correlation, and values close to zero indicate weak or no linear correlation. For example, 'Pclass' and 'Fare' show a negative correlation, suggesting that higher class tickets are generally more expensive. 'SibSp' and 'Parch' show a positive correlation, which is expected as they both relate to family size. 'Survived' shows interesting correlations with 'Pclass' (negative, higher class = more survival) and 'Fare' (positive, higher fare = more survival).")

"""### 6. Pairplot of selected numerical variables"""

numerical_vars = ['Age', 'Fare', 'SibSp', 'Parch', 'Survived']
sns.pairplot(df[numerical_vars], hue='Survived', diag_kind='kde')
plt.suptitle('Pairplot of Selected Numerical Variables by Survival Status', y=1.02)
plt.show()

print("Interpretation: The pairplot provides a matrix of scatter plots for each pair of numerical variables and histograms/KDEs for individual variables, colored by 'Survived' status. This allows us to observe relationships between variables and how they differ for survivors versus non-survivors. For instance, the diagonal plots show the distribution of each variable for survivors and non-survivors, highlighting differences in age, fare, and family size distributions.")

"""## Task 4: Statistical Analysis

### 1. Descriptive statistics
"""

print("Descriptive Statistics for Numerical Features:")
display(df.describe())

"""### 2. Frequency distribution"""

print("Frequency Distribution of Passenger Class:")
display(df['Pclass'].value_counts())
print("\nFrequency Distribution of Embarked Port:")
display(df['Embarked'].value_counts())

print("Interpretation: The frequency distribution for 'Pclass' confirms that 3rd class had the most passengers, followed by 1st and then 2nd class. For 'Embarked', the majority of passengers embarked from Southampton (S), followed by Cherbourg (C) and Queenstown (Q).")

"""### 3. Correlation analysis"""

correlation_matrix = df.corr(numeric_only=True)
print("Correlation Matrix:")
display(correlation_matrix)

"""### 4. Identification of the strongest positive correlation"""

strongest_positive_corr = correlation_matrix.unstack().sort_values(ascending=False)
strongest_positive_corr = strongest_positive_corr[strongest_positive_corr < 1]
strongest_positive_corr = strongest_positive_corr.drop_duplicates()

# Filter out self-correlations and get the top one
positive_pairs = strongest_positive_corr[strongest_positive_corr > 0]

if not positive_pairs.empty:
    strongest_positive_pair = positive_pairs.index[0]
    strongest_positive_value = positive_pairs.iloc[0]
    print(f"Strongest positive correlation: {strongest_positive_pair} with a value of {strongest_positive_value:.2f}")
else:
    print("No positive correlations found.")

"""### 5. Identify the strongest negative correlation"""

strongest_negative_corr = correlation_matrix.unstack().sort_values(ascending=True)
strongest_negative_corr = strongest_negative_corr[strongest_negative_corr < 0]
strongest_negative_corr = strongest_negative_corr.drop_duplicates()

# Filter out self-correlations and get the top one (most negative)
negative_pairs = strongest_negative_corr[strongest_negative_corr < 0]

if not negative_pairs.empty:
    strongest_negative_pair = negative_pairs.index[0]
    strongest_negative_value = negative_pairs.iloc[0]
    print(f"Strongest negative correlation: {strongest_negative_pair} with a value of {strongest_negative_value:.2f}")
else:
    print("No negative correlations found.")

"""### 6. Discuss three important statistical findings

Based on the statistical analyses performed, here are three important findings:

1.  **Passenger Class and Survival:** There is a significant negative correlation between `Pclass` (Passenger Class) and `Survived`. This suggests that passengers in lower classes (e.g., 3rd class) had a lower chance of survival compared to those in higher classes (1st class). This is also supported by the boxplot of Age by Passenger Class, where 1st class passengers generally had higher ages and potentially more resources.

2.  **Fare and Survival:** There is a positive correlation between `Fare` and `Survived`. This indicates that passengers who paid higher fares had a greater likelihood of survival. This finding is consistent with the `Pclass` correlation, as higher fares are typically associated with higher passenger classes, which had better survival rates.

3.  **Age Distribution:** The distribution of `Age` shows a median around the late 20s or early 30s, with a noticeable number of children (Age < 15) and a general decrease in passenger count for older age groups. While Age itself does not have a very strong linear correlation with `Survived`, the boxplot shows that 1st class passengers tend to be older. Further analysis could explore age groups' survival rates (e.g., children vs. adults).

## Task 5: Machine Learning

### 1. Select suitable predictor variables
"""

# For this simple classification model, we'll select a few relevant features.
# 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', and 'Fare' are good candidates.
# 'Embarked' is also categorical and potentially useful.
# We need to convert categorical features into numerical format for the model.

# Convert 'Sex' and 'Embarked' into numerical format using one-hot encoding
df_ml = df.copy()
df_ml = pd.get_dummies(df_ml, columns=['Sex', 'Embarked'], drop_first=True)

# Select predictor variables (features) and the target variable
X = df_ml[['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_male', 'Embarked_Q', 'Embarked_S']]
y = df_ml['Survived']

print("Selected predictor variables (features):")
display(X.head())
print("\nTarget variable (Survived):")
display(y.head())

"""### 2. Split the dataset into training and testing sets"""

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training features shape: {X_train.shape}")
print(f"Testing features shape: {X_test.shape}")
print(f"Training target shape: {y_train.shape}")
print(f"Testing target shape: {y_test.shape}")

from sklearn.impute import SimpleImputer

# Initialize the SimpleImputer with the median strategy
# The median is chosen to be robust to outliers in the 'Age' column.
imputer = SimpleImputer(strategy='median')

# Fit the imputer on X_train and transform both X_train and X_test
X_train_imputed = imputer.fit_transform(X_train)
X_test_imputed = imputer.transform(X_test)

# Convert the imputed arrays back to DataFrames, preserving column names
X_train = pd.DataFrame(X_train_imputed, columns=X_train.columns)
X_test = pd.DataFrame(X_test_imputed, columns=X_test.columns)

print("Missing values in X_train after imputation:")
print(X_train.isnull().sum())
print("\nMissing values in X_test after imputation:")
print(X_test.isnull().sum())

print("X_train and X_test imputed successfully.")

"""### 3. Train a Logistic Regression classifier"""

from sklearn.linear_model import LogisticRegression

# Initialize the Logistic Regression model
# Set max_iter to a higher value if it fails to converge
model = LogisticRegression(random_state=42, solver='liblinear', max_iter=200)

# Train the model on the training data
model.fit(X_train, y_train)

print("Logistic Regression model trained successfully.")

"""### 4. Predict the testing data"""

# Predict on the test set
y_pred = model.predict(X_test)

print("Predictions on the testing data generated successfully.")

"""### 5. Compute Accuracy, Confusion Matrix, Classification Report"""

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Compute Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

# Compute Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
display(pd.DataFrame(conf_matrix, index=['Actual No Survival', 'Actual Survival'], columns=['Predicted No Survival', 'Predicted Survival']))

# Compute Classification Report
class_report = classification_report(y_test, y_pred)
print("\nClassification Report:")
print(class_report)

plt.figure(figsize=(10, 6))
sns.boxplot(x='Pclass', y='Age', data=df, palette='coolwarm')
plt.title('Age Distribution by Passenger Class')
plt.xlabel('Passenger Class (1 = 1st, 2 = 2nd, 3 = 3rd)')
plt.ylabel('Age')
plt.xticks([0, 1, 2], ['1st Class', '2nd Class', '3rd Class'])
plt.grid(axis='y', alpha=0.75)
plt.show()

print("Interpretation: The boxplot illustrates the age distribution across different passenger classes. It appears that passengers in 1st class tend to be older than those in 2nd and 3rd class. The median age generally decreases from 1st to 3rd class, suggesting that higher classes might have had older, potentially wealthier, individuals.")